### ISSUE TITLE
RC5 hangs on startup.

### ISSUE THREAD

**Issue by bwegh** [indigo-dc/onedata#2] opened 2016-09-14 11:53 UTC
Similar like #1 yet this time the certificate is again the default certificate of cowboy, which can be found on [github](https://github.com/ninenines/cowboy/tree/master/examples/ssl_hello_world/priv/ssl) including the key.

I ran the openprovider again with my script and here is the [output](https://github.com/indigo-dc/onedata/files/471953/oneprovider_log.txt)

**Comment by groundnuty** [comment] 2016-09-14 16:03
@bwegh 
As your log shows the startup fails at:

```
[36moneprovider_kit                |[0m * service_onepanel: add_users
[36moneprovider_kit                |[0m Error: Service Error
[36moneprovider_kit                |[0m Description: Action 'deploy' for a service 'oneprovider' terminated with an error.
[36moneprovider_kit                |[0m Module: service_onepanel
[36moneprovider_kit                |[0m Function: add_users
[36moneprovider_kit                |[0m Hosts: node1.oneprovider.localhost
[36moneprovider_kit                |[0m For more information please check the logs.
```

adding users.
This is due to a unfortunate bug in rc5 (which I am told will be fixed in rc6). 
Please change in your configuration the names of users _admin_ and _user_ to _admin2_ and _user2_. 
A part form your log with changes needed:

```
70,71c62,63
<             "admin2":
<               password: "yourpass"
---
>             "admin1":
>               password: "yourpass"
73,74c65,66
<             "user2":
<               password: "yourpass"
---
>             "user1":
>               password: "yourpass"
```

Please give us a feedback if that solved the problem.

**Comment by bwegh** [comment] 2016-09-15 08:13
I tried, and users were added, certificates seemed to be loaded, but it hung for more than 10 minutes at
`service_op_worker: wait_for_init`

complete output:

```
Creating oneprovider_kit
Attaching to oneprovider_kit
oneprovider_kit                | Starting op_panel: [  OK  ]
oneprovider_kit                | 
oneprovider_kit                | Configuring oneprovider:
oneprovider_kit                | * service_onepanel: set_cookie
oneprovider_kit                | * service_onepanel: purge_node
oneprovider_kit                | * service_onepanel: create_tables
oneprovider_kit                | * service_onepanel: add_default_users
oneprovider_kit                | * service_onepanel: add_nodes
oneprovider_kit                | * service: save
oneprovider_kit                | * service_couchbase: configure
oneprovider_kit                | * service_couchbase: start
oneprovider_kit                | * service_couchbase: wait_for_init
oneprovider_kit                | * service_couchbase: init_cluster
oneprovider_kit                | * service_couchbase: rebalance_cluster
oneprovider_kit                | * service_couchbase: status
oneprovider_kit                | * service: save
oneprovider_kit                | * service_cluster_manager: configure
oneprovider_kit                | * service_cluster_manager: start
oneprovider_kit                | * service_cluster_manager: status
oneprovider_kit                | * service: save
oneprovider_kit                | * service_op_worker: configure
oneprovider_kit                | * service_op_worker: setup_certs
oneprovider_kit                | * service_op_worker: start
oneprovider_kit                | * service_op_worker: wait_for_init
```

I will just wait for RC6 and its documentation ...

**Comment by groundnuty** [comment] 2016-09-15 09:47
@bwegh 
I'm glad to hear that users and certs were added successfully. What kind of machine you are running it on? I doubt that rc6 will solve this issue you are experiencing, since it's the first time I see it and I do test every rc against every scenario in getting-started prior to release manually (human tester apart from integration tests that we have :) ). 
Cloud you please send us the content of /home/bas/.config/onedata/persistence/var/log/ ? 

Michal

**Comment by bwegh** [comment] 2016-09-16 10:06
ran it again, waited about 50 minutes at 'configure oneprovider'
[oneprovider_log.txt](https://github.com/indigo-dc/onedata/files/476565/oneprovider_log.txt)

[op_worker.zip](https://github.com/indigo-dc/onedata/files/476579/op_worker.zip)

**Comment by groundnuty** [comment] 2016-09-16 11:49
we need entire /var/log, not only op_worker. could you pack in and attach it here?

**Comment by bwegh** [comment] 2016-09-19 07:22
here you go ... [oneprovider.zip](https://github.com/indigo-dc/onedata/files/479430/oneprovider.zip)

**Comment by groundnuty** [comment] 2016-09-21 07:11
We are not able to reproduce what you are experiencing :(
rc6 will be out today/tomorrow - I will update this ticket when it's out.

**Comment by stefanonicotri** [comment] 2016-09-22 07:37
also in my case it never started. i have tried several times, but it always hangs on "Attaching to onezone-1" or on "onezone-1           Starting oz_panel: [  OK  ]". If I try to connect to the web interface the error is "Fatal error: session cannot be initialized"

**Comment by groundnuty** [comment] 2016-09-22 07:48
We identified this as a 'race condition' at startup. As always with concurrency bugs, they are not easy to reproduce. Suffice to say that, in my own tests it never happened :( 
One college experienced it yesterday, but he tried 2 more times and it all worked. It affects the startup, when startup passes onezone/oneprovider work as expected. 
We have found a developer responsible for it :) and it will be fixed in rc6.

**Comment by marcvs** [comment] 2016-09-29 16:36
So since it was fixed in rc6, bas could you run your tests again?

**Comment by bwegh** [comment] 2016-09-30 06:35
I did, yet it hangs now at registering as the bari zone is not running, so I will test again once the bari onezone is up.

**Comment by groundnuty** [comment] 2016-10-04 19:44
fixed since rc7.

**Closed as completed by groundnuty** 2016-10-04 19:44 UTC
Labels: bug
